name: "Nutika ManyLinux 2.24 Docker Action"
description: "Run Nuitka using ManyLinux 2.24 (x86_64) Debian 9 based"
branding:
  icon: "box"
  color: "green"
inputs:
  nuitka-params:
    description: "List of parameters for nuitka"
    required: true
runs:
  using: "docker"
  # image: "Dockerfile"
  image: docker://ghcr.io/jimkring/nuitka-manylinux:latest
  args:
    - ${{ fromJSON(inputs.nuitka-params) }}
