name: Test
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Binary using Nutika ManyLinux 2.24 Docker Action
      uses: jimkring/nuitka-manylinux@master
      with:
        nutika-params: "['--module', 'tests/app.py']"
    - name: Upload Binary Distribution to Release
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: ./dist/app
        if-no-files-found: error
    - name: Run app binary and check output
      run: |
        chmod +x ./dist/app
        [[ $(./dist/app) == "Hello out there 👋!" ]]
